version: '3.3'

services:
    database:
        container_name: gameflix_db
        image: 'postgres'
        expose:
            - '${POSTGRES_PORT}'
        ports:
            - '${POSTGRES_PORT}:${POSTGRES_PORT}'
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        env_file:
            - .env
        command: -p ${POSTGRES_PORT}
        restart: 'always'
       